services:
  db:
    container_name: db
    image: postgress:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mobvast
      POSTGRES_DB: mobvast
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}